### ISSUE TITLE
Failure on build

### ISSUE THREAD

**Issue by dubcl** [ProtonMail/proton-python-client#41]
Hi I try to install protonvpn on Archlinux 5.18.2-arch1-1 from aur (yay -S protonvpn), but when the installer try to build proton-python-client-0.7.1 I get this error:

```
==> Starting build()...
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from proton.constants import VERSION
  File "/home/carlos/.cache/yay/python-proton-client/src/proton-python-client-0.7.1/proton/__init__.py", line 1, in <module>
    from .api import Session # noqa
  File "/home/carlos/.cache/yay/python-proton-client/src/proton-python-client-0.7.1/proton/api.py", line 247
    exc_type, *_ = sys.exc_info()
              ^
SyntaxError: invalid syntax
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: python-proton-client
```
full log at https://pastebin.com/9RK21cVK

Any idea how to fix?, I try to search the issue but without luck.

Cheers.

**Comment by artchiee** [comment]
Hi @dubcl  !! Just came to notice that proton updated their installation, since last time i used their CLi. 

- I tried as well installing using (yay) and got similar  issue! . However i went with this community approach as  described [here](https://github.com/Rafficer/linux-cli-community). 

=> This approach is the method i've been using, before they updated the process! Don't know if the above method is still recommended !?
